name: pre

runs:
  using: composite
  steps:
    - name: env
      run: |
        nproc
        uname -a
        id
        cat /etc/os-release
        getent passwd
      shell: sh
    - run: env | LC_ALL=C sort
      shell: sh
