name: docker
on:
  push:
    branches: [ master ]

jobs:
  alpine-hello:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: hello
        run:
          - uname -a
          - . /etc/os-release && printf 'Hello from %s\n' "$NAME"
