name: docker

on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  alpine-hello:
    runs-on: ubuntu-latest
    container: alpine:latest
    env:
      TERM: dumb
    steps:
      - name: env
        run: |
          uname -a
          nproc
          cat /etc/os-release
      - name: hello
        run: . /etc/os-release && printf 'Hello from %s\n' "$PRETTY_NAME"
      - name: bye
        run: |
          printf 'Bye 1\n'
          printf 'Bye 2\n'
      - name: end
        run: >
          printf '%s\n' a
          b
      - run: env | LC_ALL=C sort
