name: docker
on:
  push:
    branches: [ master ]

jobs:
  alpine-hello:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: env
        run: uname -a; nproc
      - name: hello
        run: . /etc/os-release && printf 'Hello from %s\n' "$NAME"
      - run: printf 'Bye\n'
